### ISSUE TITLE
安装fis-parser-sass出错

### ISSUE THREAD

**Issue by letuer** [fex-team/fis#344]
本地环境：Win7 64位，安装nodejs v0.12。首次安装报编译错误，需要安装Windows SDK for 2008。装了以后安装继续报错，显示如下：
D:\>npm install -g fis-parser-sass
\
> fis-sass@3.1.2 install C:\Users\Unisen\AppData\Roaming\npm\node_modules\fis-parser-sass\node_modules\fis-sass
> node build.js

Downloading http://fisstatic.duapp.com/addons/fis-sass/3.1.0/win32-ia32/0.10.2/b
inding.node ...
child_process: customFds option is deprecated, use stdio instead.

C:\Users\Unisen\AppData\Roaming\npm\node_modules\fis-parser-sass\node_modules\fis-sass>node "D:\Apps\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild child_process: customFds option is deprecated, use stdio instead.
VCBUILD : error Message:
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Apps\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\Apps\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Unisen\AppData\Roaming\npm\node_modules\fis-parser-sass\node_modules\fis-sass
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Apps\\NodeJS\\\\node.exe" "D:\\Apps\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "fis-parser-sass"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! fis-sass@3.1.2 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fis-sass@3.1.2 install script 'node build.js'.
npm ERR! This is most likely a problem with the fis-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fis-sass
npm ERR! There is likely additional logging output above.

对npm刚入门，在网上也没找到合适的答案，求教！！！
顺祝新年快乐~~
~~~~~~~~~~~~我是大年初一就学习的好少年……

**Comment by xiangshouding** [comment]
#331 还没有全部适配，所以需要降级你的node版本到0.10.x

**Comment by Megasu** [comment]
closed #344
