### ISSUE TITLE
fis 安装报错

### ISSUE THREAD

**Issue by orzzzl** [fex-team/fis#345]
我是第一次安装fis，安装的时候报错了。。 
p.s. 为什么最新版本还是dev版本？

TicTacToe-gh-pages  sudo npm install fis -g
Password:
 
> images@2.1.1 install /usr/local/lib/node_modules/fis/node_modules/fis-spriter-csssprites/node_modules/images
> (node ./install.js 2> builderror.log) || (exit 0)

Downloading https://raw.githubusercontent.com/zhangyuanwei/node-images/master/bindings/darwin/x64/0.9.11/binding.node
Received 514K...
Received 514K total.
 
> fsevents@0.3.5 install /usr/local/lib/node_modules/fis/node_modules/fis-command-release/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from /usr/include/dispatch/dispatch.h:51:0,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:55,
                 from ../fsevents.cc:10:
/usr/include/dispatch/object.h:143:15: error: expected unqualified-id before '^' token
/usr/include/dispatch/object.h:143:15: error: expected ')' before '^' token
/usr/include/dispatch/object.h:362:17: error: 'dispatch_block_t' has not been declared
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55:0,
                 from ../fsevents.cc:11:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262:1: error: expected '}' before '__attribute__'
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262:89: error: expected unqualified-id before '=' token
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414:1: error: expected '}' before '__attribute__'
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414:89: error: expected unqualified-id before '=' token
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:481:1: error: expected declaration before '}' token
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/fis/node_modules/fis-command-release/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
 
> fsevents@0.3.5 install /usr/local/lib/node_modules/fis/node_modules/fis-command-server/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from /usr/include/dispatch/dispatch.h:51:0,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:55,
                 from ../fsevents.cc:10:
/usr/include/dispatch/object.h:143:15: error: expected unqualified-id before '^' token
/usr/include/dispatch/object.h:143:15: error: expected ')' before '^' token
/usr/include/dispatch/object.h:362:17: error: 'dispatch_block_t' has not been declared
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55:0,
                 from ../fsevents.cc:11:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262:1: error: expected '}' before '__attribute__'
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262:89: error: expected unqualified-id before '=' token
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414:1: error: expected '}' before '__attribute__'
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414:89: error: expected unqualified-id before '=' token
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:481:1: error: expected declaration before '}' token
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/fis/node_modules/fis-command-server/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.5
npm WARN optional dep failed, continuing fsevents@0.3.5
/usr/local/bin/fis -> /usr/local/lib/node_modules/fis/bin/fis
fis@1.9.7-dev /usr/local/lib/node_modules/fis
├── fis-preprocessor-components@1.0.15
├── fis-prepackager-derived@0.0.3
├── fis-postprocessor-jswrapper@0.0.9
├── fis-deploy-default@0.0.2
├── fis-packager-map@0.0.9
├── colors@0.6.2
├── commander@1.3.2 (keypress@0.1.0)
├── fis-optimizer-clean-css@0.0.9 (clean-css@1.1.7)
├── fis-optimizer-uglify-js@0.1.6 (uglify-js@2.4.15)
├── fis-spriter-csssprites@0.2.7 (images@2.1.1)
├── fis-kernel@2.0.12 (iconv-lite@0.2.10, tar@0.1.17)
├── fis-command-install@0.1.16 (progress-bar@0.1.1, progress@1.1.8, findup@0.1.5, semver@4.3.1, bluebird@2.9.12, request@2.53.0, fis-scaffold-kernel@0.0.20)
├── fis-command-release@0.11.4 (async@0.9.0, livereload-server-spec@0.2.3, chokidar@0.12.5)
├── fis-command-server@0.7.1 (step@0.0.5, chokidar@0.10.5)
└── fis-optimizer-png-compressor@0.0.7 (node-pngquant-native@0.1.0, node-pngcrush@0.1.3)
➜  TicTacToe-gh-pages  fis

  Usage: fis <command>

  Commands:

    release     build and deploy your project
    install     install components
    server      launch a php-cgi server

  Options:

    -h, --help     output usage information
    -v, --version  output the version number
    --no-color     disable colored output

➜  TicTacToe-gh-pages  fis -v

  v1.9.7-dev

 __/\\\\\\\\\\\\\\\__/\\\\\\\\\\\_____/\\\\\\\\\\\___
  _\/\\\///////////__\/////\\\///____/\\\/////////\\\_       
   _\/\\\_________________\/\\\______\//\\\______\///__
    _\/\\\\\\\\\\\_________\/\\\_______\////\\\_________     
     _\/\\\///////__________\/\\\__________\////\\\______    
      _\/\\\_________________\/\\\_____________\////\\\___   
       _\/\\\_________________\/\\\______/\\\______\//\\\__
        _\/\\\______________/\\\\\\\\\\\_\///\\\\\\\\\\\/___
         _\///______________\///////////____\///////////_____

➜  TicTacToe-gh-pages

**Comment by xiangshouding** [comment]
应该不影响使用

**Comment by orzzzl** [comment]
那为啥版本是dev啊？

**Comment by xiangshouding** [comment]
因为还没有支持linux 32下的node 0.12.0
