### ISSUE TITLE
错误不详细的问题

### ISSUE THREAD

**Issue by trainGitHub** [fex-team/fis#351]
异常信息
HTTP ERROR 500

Problem accessing /home/page/index. Reason:

    Server Error
Caused by:

java.lang.RuntimeException: PHP Fatal error:  Uncaught exception 'SmartyException' with message 'Unable to load template file '/Users/abc/.fis-plus-tmp/www/template/home/page/index.tpl'' in /Users/abc/.fis-plus-tmp/www/smarty/sysplugins/smarty_internal_templatebase.php:127
Stack trace:
#0 /Users/abc/.fis-plus-tmp/www/smarty/sysplugins/smarty_internal_templatebase.php(374): Smarty_Internal_TemplateBase->fetch('/Users/abc/.f...', NULL, NULL, NULL, true)
#1 /Users/abc/.fis-plus-tmp/www/fisdata/TestData.class.php(100): Smarty_Internal_TemplateBase->display('/Users/abc/.f...')
#2 /Users/abc/.fis-plus-tmp/www/index.php(53): TestData::renderHelper(Object(Smarty), '/Users/abc/.f...')
#3 /Users/abc/.fis-plus-tmp/www/index.php(146): fis_debug_render_smarty()
#4 {main}
  thrown in /Users/abc/.fis-plus-tmp/www/smarty/sysplugins/smarty_internal_templatebase.php on line 127

	at php.java.servlet.fastcgi.FastCGIServlet.parseBody(FastCGIServlet.java:409)
	at php.java.servlet.fastcgi.FastCGIServlet.execute(FastCGIServlet.java:433)
	at php.java.servlet.fastcgi.FastCGIServlet.handle(FastCGIServlet.java:481)
	at php.java.servlet.fastcgi.FastCGIServlet.doGet(FastCGIServlet.java:521)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at com.baidu.fis.HttpServer$FISWebAppContext.doScope(HttpServer.java:106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:695)

访问页面会报上面的错，但是编译是没有错的。
后来定位到错误是fis-conf.js里的配置引起的，但是这配置是抄来的应该没错。请教这问题出在哪？
fis.config.set('roadmap.path', [
    {
        reg: '**.css',
        useSprite: true
    }
]);
fis.config.set('settings.spriter.csssprites.margin', 10);

**Comment by xiangshouding** [comment]
set 导致默认的roadmap.path被覆盖了，请用 fis.config.get("roadmap.path").unshift({
     reg: /某正则/,
     ...
})

**Comment by trainGitHub** [comment]
嗯，错误搞定了多谢。但是csssprites不生效可能是什么原因？用的是fisp, 在图片后面加了参数 ?__sprite。 然后样式是scss文件，可能是这个原因吗？

**Comment by ayu2012** [comment]
我的还是打包和合并用不起 求解决 用的官方的demo发自网易邮箱大师
            在2015年02月27日 09:46，trainGitHub 写道:嗯，错误搞定了多谢。但是csssprites不生效可能是什么原因？用的是fisp, 在图片后面加了参数 ?__sprite。 然后样式是scss文件，可能是这个原因吗？
