### ISSUE TITLE
开启了两个fis项目，可以做到两个项目都可以同步刷新吗？

### ISSUE THREAD

**Issue by 7demo** [fex-team/fis#391]
由于某种原因，不得不同时运行两个项目。同步刷新功能舍弃不掉，于是尝试在两个项目中去运行<code>fis release -wL</code>。第一个成功，第二个报错：
<pre>
C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis\node_modules\fis-com
mand-release\release.js:289
                    if(err.message !== 'read ECONNRESET') throw  err;
                                                                 ^
Error: LiveReload server Listening failed: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
    at LRWebSocketServer.listen (C:\Users\Administrator\AppData\Roaming\npm\node
_modules\fis\node_modules\fis-command-release\node_modules\livereload-server-spe
c\lib\server.js:62:32)
    at Command.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modu
les\fis\node_modules\fis-command-release\release.js:280:26)
    at Command.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modu
les\fis\node_modules\commander\index.js:256:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (C:\Users\Administrator\AppData\Roaming\npm\node_module
s\fis\node_modules\commander\index.js:479:12)
    at Command.parse (C:\Users\Administrator\AppData\Roaming\npm\node_modules\fi
s\node_modules\commander\index.js:377:21)
</pre>

由于fis server在启动的时候，可以通过指定端口来启动多个。那么liveload是否可以通过指定端口，来运行多个呢？

**Comment by xiangshouding** [comment]
```js
fis.config.set('livereload.port', '8999');
```

**Comment by 7demo** [comment]
@xiangshouding 谢谢，已解决。
