### ISSUE TITLE
[FAQ]fis-parser-sass安装失败求助

### ISSUE THREAD

**Issue by chokcoco** [fex-team/fis#405]
所有要求的编译环境都已经搭建好了。
最后还是报错如下：

C:\Users\Administrator>npm install fis-parser-sass -g
npm http GET https://registry.npmjs.org/fis-parser-sass
npm http 304 https://registry.npmjs.org/fis-parser-sass
npm http GET https://registry.npmjs.org/fis-sass
npm http 304 https://registry.npmjs.org/fis-sass
npm ERR! Error: No compatible version found: fis-sass@'^3.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.4","0.1.7","0.1.8","0.1.9","0.1.10","0.1.11","0.1.12","0.1.13","0
.1.14","0.1.15","0.1.17","0.2.0-beta","0.2.0","3.1.0","3.1.1","3.1.2"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\li
b\cache.js:682:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:597:10
npm ERR!     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm
-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "fis-parser-sass" "-g"
npm ERR! cwd C:\Users\Administrator
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Administrator\npm-debug.log
npm ERR! not ok code 0

请问是什么回事？

**Comment by chokcoco** [comment]
npm ERR! Error: No compatible version found: fis-sass@'^3.1.0'
不知道是否主要出错在这，无法get到这个fis-sass的版本，是否跟npm经常被墙有关系？
另外，我之前是用node v0.12安装失败，再降到node v0.10的，还是不行

**Comment by xiangshouding** [comment]
npm 版本太老了，不认识 `^3.1.0` 的版本。
