### ISSUE TITLE
输入fis server start --type node报错Cannot find module 'merge-descriptors'

### ISSUE THREAD

**Issue by duolew** [fex-team/fis#413]
$ fis server start --type node
starting fis-server .. fail
module.js:338
    throw err;
          ^
Error: Cannot find module 'merge-descriptors'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\鹏\AppData\Local\.fis-tmp\www\node_modules\express\lib\express.js:6:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

 [ERROR] Cannot find module 'merge-descriptors'

我输入fis server start --type node    不行啊········不知道哪里错了 有人能帮一下吗 谢谢

**Comment by xiangshouding** [comment]
近期修复

**Comment by xiangshouding** [comment]
待发布
