### ISSUE TITLE
Error: EISDIR, illegal operation on a directory

### ISSUE THREAD

**Issue by jsers** [fex-team/fis#422]
fs.js:554
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR, illegal operation on a directory
    at Error (native)
    at Object.fs.readSync (fs.js:554:19)
    at Object.fs.readFileSync (fs.js:386:28)
    at Function._.read (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:445:22)
    at Object.derive.getContent (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/file.js:263:38)
    at prepareDeploy (/usr/local/lib/node_modules/fis/node_modules/fis-command-release/lib/deploy.js:53:28)
    at /usr/local/lib/node_modules/fis/node_modules/fis-command-release/lib/deploy.js:138:13
    at /usr/local/lib/node_modules/fis/node_modules/fis-command-release/node_modules/async/lib/async.js:570:21
    at /usr/local/lib/node_modules/fis/node_modules/fis-command-release/node_modules/async/lib/async.js:249:17
    at replenish (/usr/local/lib/node_modules/fis/node_modules/fis-command-release/node_modules/async/lib/async.js:194:21)

**Comment by hefangshi** [comment]
建议提Issue的时候多包含一些信息。

你的问题据我猜测，是源代码中有一个文件A，而部署路径中有一个个文件夹B，导致部署的时候提示目标路径是一个文件夹而不是文件。

把部署路径删除后重新部署就可以解决了。
