### ISSUE TITLE
在mac 10.10.3下安装出错

### ISSUE THREAD

**Issue by zikkeung** [fex-team/fis#464]
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:24:10: fatal error: 'node.h' file not found
#include <node.h>
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/fis/node_modules/fis-command-server/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.2
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN optional dep failed, continuing fsevents@0.3.6

**Comment by xiangshouding** [comment]
嗯；这个就奇怪了，如果没有 node 源码，安装的时候会自动下载。
