### ISSUE TITLE
建议做一个开发fis插件的视频教程

### ISSUE THREAD

**Issue by w2230030100** [fex-team/fis#535]
最近想学习开发下fis的拓展插件 但是无从下手 看fis的官方文档感觉只教写法 并不会一个完整的流程 所以求视频教程 希望大神们有空的时候忙里偷闲做一套 谢谢

**Comment by xiangshouding** [comment]
是否看了运行原理以及插件扩展点这两篇文档？

https://github.com/fex-team/fis/wiki/%E6%8F%92%E4%BB%B6%E8%B0%83%E7%94%A8%E6%9C%BA%E5%88%B6
https://github.com/fex-team/fis/wiki/%E8%BF%90%E8%A1%8C%E5%8E%9F%E7%90%86

**Comment by xiangshouding** [comment]
或者这篇

http://fis.baidu.com/docs/dev/intro.html

**Comment by w2230030100** [comment]
看了 但是不知道如何从头开始操作 说白了就是我不知道我应该怎么下手 = =！有个视频教程或者详细的文字教程啥的手把手从头到尾带一遍才好了 请求大神如果有空的时候做一个 谢谢 谢谢

**Comment by xiangshouding** [comment]
嗯，好，我重写这块的文档；

**Comment by w2230030100** [comment]
@xiangshouding 太感谢了 膜拜大神 如果学习好了我也为fis尽一份力

**Comment by xiangshouding** [comment]
http://fis.baidu.com/docs/dev/plugin.html  等会儿你访问这篇文稿即可，如果等不及就直接访问；

https://github.com/fex-team/fis-site/blob/master/docs/dev/plugin.md

有问题再咨询

**Comment by w2230030100** [comment]
@xiangshouding 大神周一好 我按照教程从头做 我在本地软链了npm全局文件夹到开发目录 然后见了个测试的文件夹不知道为什么想截图发不上来

index.js是复制的less的
package.json内容如下
```
{
  "name": "fis-parser-wabc",
  "version": "1.0.1",
  "description": "A parser for fis to w22300 test dev",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": {
    "name": "w2230030100"
  },
  "keywords": [
    "fis",
    "wabc"
  ],
  "license": "MIT",
  "dependencies": {
    "less": "1.7.5"
  },
  "readme": "w2230030100 test less",
  "readmeFilename": "README.md",
  "_id": "fis-parser-wabc@1.0.1",
  "_shasum": "203183d0992c83738be8c09884857a266e9dcad1",
  "_from": "fis-parser-wabc@*"
}
```
然后我见了个目录测试release报错
```
bogon:lesste ningfujun$ fis release

 Ω .
 [ERROR] unable to load plugin [fis-parser-wabc]
```
fis.conf.js内容如下
```
fis.config.set("modules.parser.less","wabc");
fis.config.set("roadmap.ext.less","css");
```
为什么未找到我测试的那个wabc呢

**Comment by xiangshouding** [comment]
fis release --verbose 看看错在哪儿～

**Comment by w2230030100** [comment]
```
bogon:lesste ningfujun$ fis release --verbose

 [DEBUG] 12:33:24.0898 revert cache

 [DEBUG] 12:33:24.0901 cache file exists

 [DEBUG] 12:33:24.0902 cache info read

 [DEBUG] 12:33:24.0902 cache is valid

 [DEBUG] 12:33:24.0902 revert cache finished

 Ω 
 [DEBUG] 12:33:24.0909 compile [/Users/ningfujun/work/learn/npmdev/lesste/a.less] start

 [DEBUG] 12:33:24.0909 revert cache

 [DEBUG] 12:33:24.0909 cache is expired

 [ERROR] unable to load plugin [fis-parser-wabc]
/usr/local/lib/node_modules/fis/node_modules/fis-command-release/release.js:175
                throw e;
                      ^
Error: unable to load plugin [fis-parser-wabc]
    at Object.exports.error (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/log.js:57:15)
    at Object.fis.require (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/fis-kernel.js:93:13)
    at /usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:701:33
    at Array.forEach (native)
    at Function._.pipe (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:697:20)
    at pipe (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/compile.js:305:14)
    at process (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/compile.js:279:9)
    at Object.module.exports [as compile] (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/compile.js:36:17)
    at /usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/release.js:51:20
    at Function._.map (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:129:23)
bogon:lesste ningfujun$ 
```
我没看懂= =！ 求大神告知

**Comment by xiangshouding** [comment]
首先确认位置是否放对
然后确认插件以来的包下载安装了吗
再次看看你 fis 版本，我记得优化过这块的提示

**Comment by w2230030100** [comment]
![image](https://cloud.githubusercontent.com/assets/6111324/8153976/b8d70518-1367-11e5-8542-09637e5dc4fe.png)
![image](https://cloud.githubusercontent.com/assets/6111324/8153983/db7696ce-1367-11e5-94d5-c5f1b4655f39.png)
这个是位置

![image](https://cloud.githubusercontent.com/assets/6111324/8153996/f6dc9c42-1367-11e5-9d30-90caa394212a.png)
less依赖已装

![image](https://cloud.githubusercontent.com/assets/6111324/8154000/09173e94-1368-11e5-8ee8-65e49473a9aa.png)
fis刚更新了一遍

但是还是不行😭 
```
bogon:lesste ningfujun$ fis release --verbose

 [DEBUG] 14:02:35.0153 revert cache

 [DEBUG] 14:02:35.0156 cache file exists

 [DEBUG] 14:02:35.0157 cache info read

 [DEBUG] 14:02:35.0157 cache is valid

 [DEBUG] 14:02:35.0157 revert cache finished

 Ω 
 [DEBUG] 14:02:35.0161 compile [/Users/ningfujun/work/learn/npmdev/lesste/a.less] start

 [DEBUG] 14:02:35.0162 revert cache

 [DEBUG] 14:02:35.0162 cache is expired

 [ERROR] unable to load plugin [fis-parser-wabc]
/usr/local/lib/node_modules/fis/node_modules/fis-command-release/release.js:175
                throw e;
                      ^
Error: unable to load plugin [fis-parser-wabc]
    at Object.exports.error (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/log.js:57:15)
    at Object.fis.require (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/fis-kernel.js:93:13)
    at /usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:701:33
    at Array.forEach (native)
    at Function._.pipe (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:697:20)
    at pipe (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/compile.js:305:14)
    at process (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/compile.js:279:9)
    at Object.module.exports [as compile] (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/compile.js:36:17)
    at /usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/release.js:51:20
    at Function._.map (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:129:23)
```

**Comment by xiangshouding** [comment]
教你个调试方法，到 NPM 全局安装的那个目录下，就是安装 FIS 的哪个目录下；启用 node 命令，然后 require 你的写的插件，看报啥错？

```bash
$ cd $(npm prefix -g)/lib/node_modules
$ node
> require('fis-parser-wabc')
```

**Comment by w2230030100** [comment]
```
> require('fis-parser-wabc')
ReferenceError: fis is not defined
    at Object.<anonymous> (/Users/ningfujun/npm/lib/node_modules/fis-parser-wabc/index.js:10:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
```
我的报这个错误 因为我index.js是复制的less的 所以我又试了下less的包 也报同样的错误
```
> require('fis-parser-less')
ReferenceError: fis is not defined
    at Object.<anonymous> (/Users/ningfujun/npm/lib/node_modules/fis-parser-less/index.js:10:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
> 
```
然后我看fis未定义我把文件的开头套了个这个
```
var fis = require('fis');
```
结果报错出这个
```
> require('fis-parser-wabc')

 [ERROR] undefined project root
```

**Comment by xiangshouding** [comment]
@w2230030100 

嗯，对，里面用到了 `fis` 这个全局变量，你的做法是对的，那么你现在可以贴一下 index.js 的内容了。我猜你是不是你插件依赖的 less 没有安装？

**Comment by xiangshouding** [comment]
https://github.com/fex-team/fis-kernel/blob/master/fis-kernel.js#L92-L94 把你安装的 FIS 对应这段代码改成

```js
throw e;
```

然后看看能否报出准确的错？后我增强一下报错机制

**Comment by w2230030100** [comment]
```
/*
 * fis
 * http://fis.baidu.com/
 */

'use strict';

var fis  = require('fis'); 
var less = require('less');
var root = fis.project.getProjectPath();

module.exports = function(content, file, conf){
    conf.paths = [ file.dirname, root ];
    if (conf.syncImport === undefined) conf.syncImport = true;
    if (conf.relativeUrls === undefined) conf.relativeUrls = true;
    var parser = new(less.Parser)(conf);
    parser.parse(content, function (err, tree) {
        if(err){
            throw err;
        } else {
            if(parser.imports){
                fis.util.map(parser.imports.files, function(path){
                    file.cache.addDeps(path);
                });
            }
            content = tree.toCSS(conf);
        }
    });
    return content;
};
```
我index.js就事复制的less的那个 

![image](https://cloud.githubusercontent.com/assets/6111324/8154405/6aadd600-136c-11e5-956e-0bb3daf1118f.png)
我看依赖是less的我都装了

我这个就是带有您说的这个throw e的版本的fis
但是我发现个问题不知道有没有关系 我电脑里有个.npm的文件夹在我的用户目录下
![image](https://cloud.githubusercontent.com/assets/6111324/8154493/588de266-136d-11e5-8589-47051f94cd3f.png)

这个目录里面也都是fis啥的npm包 跟这个有关系吗 我不是太懂

**Comment by xiangshouding** [comment]
```bash
$ which fis
$ fis -v
```
> 请提供以上命令执行结果

另外，我可能刚才说得不太清楚，在插件里面不需要再去 `require('fis')` ，只是刚才测试插件是否能加载这块由于其不是在 fis 的环境中执行的，所以需要提前 require 一下，比如；

```bash
$ mkdir /tmp/debug
$ node
> require('fis')
> fis.project.setProjectRoot('/tmp/debug')
> require('fis-parser-wabc')
```

而不是把 `require('fis')` 写到**插件**中；

请检测以上代码看看输出是啥？

**Comment by w2230030100** [comment]
```
bogon:node_modules ningfujun$ which fis
/usr/local/bin/fis
bogon:node_modules ningfujun$ fis -v

  v1.9.19

 __/\\\\\\\\\\\\\\\__/\\\\\\\\\\\_____/\\\\\\\\\\\___
  _\/\\\///////////__\/////\\\///____/\\\/////////\\\_       
   _\/\\\_________________\/\\\______\//\\\______\///__
    _\/\\\\\\\\\\\_________\/\\\_______\////\\\_________     
     _\/\\\///////__________\/\\\__________\////\\\______    
      _\/\\\_________________\/\\\_____________\////\\\___   
       _\/\\\_________________\/\\\______/\\\______\//\\\__
        _\/\\\______________/\\\\\\\\\\\_\///\\\\\\\\\\\/___
         _\///______________\///////////____\///////////_____

```
那个我一回车就运行了 我用分号隔开的 不知道行不行 最会出来个浅蓝色的[Function]
```
require('fis');fis.project.setProjectRoot('/Users/ningfujun/npm/lib/node_modules');require('fis-parser-wabc')
[Function]
```

**Comment by xiangshouding** [comment]
这么说插件挂载是 OK 的；另外你不是刚更新了最新的吗，怎么还是 `1.9.19` ？

应该是其他什么原因，我猜；

```bash
$ echo $NODE_PATH
```

看输出什么？

**Comment by w2230030100** [comment]
```
bogon:node_modules ningfujun$ echo $NODE_PATH

bogon:node_modules ningfujun$ echo $NODE_PATH

啥也没有呢😂
```
您一说这个我想起来件事情 以前我看fis的时候看到有个叫spmx的一个项目 我打开里面看到有个教程说修改了xxx的东西后每次安装npm包就不用输入sudo了就是这个
![image](https://cloud.githubusercontent.com/assets/6111324/8154945/d2b55c46-1371-11e5-9f4c-e3c37b867335.png)
后来我装完发现没啥用 还得sudo安装 我就没理会这事 我这个情况是不是跟这个有关

**Comment by xiangshouding** [comment]
```bash
$ echo -e '\n export NODE_PATH=$(npm prefix -g)/lib/node_modules' >> ~/.bashrc && source ~/.bashrc
```
执行这个后试试？

**Comment by w2230030100** [comment]
```
bogon:node_modules ningfujun$ echo -e '\n export NODE_PATH=$(npm prefix -g)/lib/node_modules' >> ~/.bashrc && source ~/.bashrc
bogon:node_modules ningfujun$ ls
fis		fis-parser-wabc	jello		node-gyp
fis-parser-less	fsevents	less		spmx
bogon:node_modules ningfujun$ echo $NODE_PATH
/Users/ningfujun/npm/lib/node_modules
bogon:node_modules ningfujun$ cd /Users/ningfujun/work/learn/npmdev/lesste
bogon:lesste ningfujun$ ls
a.less		fis-conf.js
bogon:lesste ningfujun$ fis release

 δ 0ms

 Ω . 145ms
bogon:lesste ningfujun$ 
```
膜拜大神！🙏🙏🙏🙏🙏🙏
太感谢了 再不行我都要重装mac系统了 大神就是大神 太厉害了
