### ISSUE TITLE
【已解决】jello server start 失败

### ISSUE THREAD

**Issue by ystarlongzi** [fex-team/fis#569]
在执行了 `jello server update` 后，再执行 `jello server start`，报一下错误。然后卸载 jello，再重新安装 jello ，仍然报下面的错误
```
$ jello server start -p 1221
checking java support : v1.6.0
starting fis-server.
...................... fail
2015-6-26 7:30:59 org.apache.coyote.AbstractProtocol init
��Ϣ: Initializing ProtocolHandler ["http-bio-8080"]
2015-6-26 7:30:59 org.apache.catalina.core.StandardService startInternal
��Ϣ: Starting service Tomcat
2015-6-26 7:30:59 org.apache.catalina.core.StandardEngine startInternal
��Ϣ: Starting Servlet Engine: Apache Tomcat/7.0.50
2015-6-26 7:30:59 org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
��Ϣ: No global web.xml found
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jstl/core_rt is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jstl/core is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jsp/jstl/core is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jstl/fmt_rt is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jstl/fmt is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jsp/jstl/fmt is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jsp/jstl/functions is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://jakarta.apache.org/taglibs/standard/permittedTaglibs is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://jakarta.apache.org/taglibs/standard/scriptfree is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jstl/sql_rt is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jstl/sql is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jsp/jstl/sql is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jstl/xml_rt is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jstl/xml is already defined
2015-6-26 7:31:02 org.apache.catalina.startup.TaglibUriRule body
��Ϣ: TLD skipped. URI: http://java.sun.com/jsp/jstl/xml is already defined
2015-6-26 7:31:02 org.apache.tomcat.websocket.server.WsSci onStartup
��Ϣ: JSR 356 WebSocket (Java WebSocket 1.0) support is not available when running on Java 6. To suppress this message, run Tomcat on Java 7, remove the WebSocket JARs from $CATALINA_HOME/lib or add the WebSocketJARs to the tomcat.util.scan.DefaultJarScanner.jarsToSkip property in $CATALINA_BASE/conf/catalina.properties. Note that the deprecated Tomcat 7 WebSocket API will be available. 
2015-6-26 7:31:02 org.apache.catalina.core.ApplicationContext log
��Ϣ: No Spring WebApplicationInitializer types detected on classpath
2015-6-26 7:31:02 org.apache.catalina.core.StandardContext listenerStart
����: Exception sending context initialized event to listener instance of class com.baidu.fis.servlet.MapListener
java.lang.NoSuchMethodError: com.baidu.fis.util.Settings.getMapDir()Ljava/lang/String;
	at com.baidu.fis.util.MapCache.reloadMap(MapCache.java:17)
	at com.baidu.fis.util.MapCache.init(MapCache.java:161)
	at com.baidu.fis.servlet.MapListener.contextInitialized(MapListener.java:40)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4961)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5455)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)


 [ERROR] fis-server fails to start at port [1221], error: unknown
```

**Comment by 2betop** [comment]
应该是 jar 文件串了，执行 `jello server open` 你把 www/WEB-INF/lib 目录下删了(干掉老版本的 jar 文件)，然后重新执行 `jello server update`

**Comment by ystarlongzi** [comment]
@2betop tks，按照你的方法解决了。
