### ISSUE TITLE
本地环境预览

### ISSUE THREAD

**Issue by lys829** [fex-team/fis#580]
因为后台模板(jinja)的原因, 每次预览都需要手动```pure release -d ../build```一次,才能在项目的服务器环境中预览(监听文件变化只能发布在fis指定的默认环境中), 能否改动默认的fis默认的release目录,或者是有其他方案,求解答!!

**Comment by xiangshouding** [comment]
搜 issue ，有回答过这个问题

发自我的 iPhone

**Comment by lys829** [comment]
#390 是这个吗?

**Comment by xiangshouding** [comment]
不是

```
fis.config.set('deploy.preview', {
  from: '/',
  to: '../build'
});
```

**Comment by lys829** [comment]
非常感谢!! 差点就放弃了,不过我在文档里面好像没有看见这个配置项?

**Comment by lys829** [comment]
```
{
                //目录下的所有jinja文件
                reg : '**.jinja',
                release: '../temp$&',
                isHtmlLike : true
            }
```
添加isHtmlLike后编译的过程会报错```[ERROR] undefined is not a function```,

**Comment by xiangshouding** [comment]
配置 jinja 的预处理插件了吗？

```
fis release --verbose
```
添加 `--verbose` 插件，可以看到具体错误在什么地方。

**Comment by lys829** [comment]
在插件列表里面没有看到jinja的预处理插件

**Comment by xiangshouding** [comment]
那你看那块报的错吧

**Comment by lys829** [comment]
```
 [DEBUG] 10:47:41.0232 [postpackager.autoload] start

 [ERROR] undefined is not a function
/usr/local/lib/node_modules/fis-pure/node_modules/fis/node_modules/fis-command-release/release.js:175
                throw e;
                      ^
TypeError: undefined is not a function
    at injectCss (/usr/local/lib/node_modules/fis-pure/node_modules/fis-postpackager-autoload/index.js:86:21)
    at injectAutoLoad (/usr/local/lib/node_modules/fis-pure/node_modules/fis-postpackager-autoload/index.js:353:19)
    at /usr/local/lib/node_modules/fis-pure/node_modules/fis-postpackager-autoload/index.js:374:13
    at Function._.map (/usr/local/lib/node_modules/fis-pure/node_modules/fis/node_modules/fis-kernel/lib/util.js:129:23)
    at module.exports (/usr/local/lib/node_modules/fis-pure/node_modules/fis-postpackager-autoload/index.js:372:14)
    at cb (/usr/local/lib/node_modules/fis-pure/node_modules/fis/node_modules/fis-kernel/lib/release.js:99:9)
    at /usr/local/lib/node_modules/fis-pure/node_modules/fis/node_modules/fis-kernel/lib/util.js:710:17
    at Array.forEach (native)
    at Function._.pipe (/usr/local/lib/node_modules/fis-pure/node_modules/fis/node_modules/fis-kernel/lib/util.js:697:20)
    at Object.module.exports [as release] (/usr/local/lib/node_modules/fis-pure/node_modules/fis/node_modules/fis-kernel/lib/release.js:115:14)
```
这.. 我看不出什么原因

**Comment by hefangshi** [comment]
```
fis.config.set('project.fileType.text', 'jinja');
```

需要让 `FIS` 将 jinja 识别问文本文件。

**Comment by lys829** [comment]
可以了, 谢谢!!

**Comment by lys829** [comment]
这样配置后,jinja文件不支持三种语言能力,资源定位无法实现

**Comment by xiangshouding** [comment]
@lys829 因为你最终要把 jinja 编译成 js 来使用，所以需要使用 js 里面的定位能力方法。这个在这块是不太合理。
