### ISSUE TITLE
上传错误 搞了半天没搞好

### ISSUE THREAD

**Issue by gwyy** [fex-team/fis#612]
项目编译好后 通过php文件上传到真正的项目的文件夹里面 但是 感觉已经上传好了  但是又提示错误  
 Ω ... 115ms
/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/log.js:63
        throw err
              ^
Error: upload file [/map.json] to [/opt/www/kaluli/apps/kalulimobile/fis_view] by receiver [http://192.168.8.80/receiver.php] error [i0]
    at Object.exports.error (/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/log.js:57:15)
    at /usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-deploy-default/index.js:76:25
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/util.js:835:21)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
>>>>>>>>>>All modules is released!<<<<<<<<<<<

**Comment by xiangshouding** [comment]
你改动了那个 PHP 脚本？

**Comment by gwyy** [comment]
没有 直接复制的 啥都没动

**Comment by xiangshouding** [comment]
贴出来看看

**Comment by gwyy** [comment]
天呐。。真的有改  <?php 前面多了个 i  变成了  i<?php  谢谢大神
