### ISSUE TITLE
MAC 中会出现fis server stop 无法停止java进程继而无法停止服务

### ISSUE THREAD

**Issue by raybest** [fex-team/fis#614]
checking java support : v1.8.0
checking php-cgi support : v5.6.11
starting fis-server .... fail
2015-07-21 10:51:08.247:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2015-07-21 10:51:08.404:WARN:oejuc.AbstractLifeCycle:FAILED SelectChannelConnector@0.0.0.0:8080: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.Server.doStart(Server.java:293)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at com.baidu.fis.HttpServer.<init>(HttpServer.java:119)
	at com.baidu.fis.HttpServer.main(HttpServer.java:58)
2015-07-21 10:51:08.405:WARN:oejuc.AbstractLifeCycle:FAILED org.eclipse.jetty.server.Server@3a82f6ef: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.Server.doStart(Server.java:293)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at com.baidu.fis.HttpServer.<init>(HttpServer.java:119)
	at com.baidu.fis.HttpServer.main(HttpServer.java:58)

 [ERROR] fis-server fails to start at port [8080], error: Address already in use

**Comment by xiangshouding** [comment]
```
pkill -9 java
```

**Comment by xiangshouding** [comment]
后，我们复现后修复。

**Comment by raybest** [comment]
另外， fis server --root /xxxx 并不能修改默认http://127.0.0.1:8080的默认路径

**Comment by xiangshouding** [comment]
@raybest 哪个版本？

**Comment by raybest** [comment]
OS X 10.10.4, nodejs fis 都是最新的，java 和 php 见最上面的。
