### ISSUE TITLE
fis release异常： Cannot read property 'useAutoload' of undefined

### ISSUE THREAD

**Issue by yongsudehanzi** [fex-team/fis#662]
大家好，小弟根据官方https://github.com/fex-team/fis-amd-demo 运行fis release 
出现错误： [ERROR] Cannot read property 'useAutoload' of undefined
请问各位大神有没有遇到这种情况，解决方案能够告诉小弟，不甚感激！
附加配置：win7 64位  nodejs0.11.16（原先装0.10.34也存在此问题）

![default](https://cloud.githubusercontent.com/assets/14308649/9901882/f2c47ba6-5c9c-11e5-8675-6cf1c3e6b66d.jpg)

**Comment by yongsudehanzi** [comment]
有人能告诉我吗？急

**Comment by 2betop** [comment]
`--verbose` 看看详细信息，另外 csssprite 不支持 0.11 的版本，用 0.10.x 或者 0.12.x

**Comment by yongsudehanzi** [comment]
恕我愚昧，我尝试着--verbose，请问这是什么错误？有什么解决方法

由于图片上传出错 这里给出错误代码
 [DEBUG] 10:59:02.0074 [prepackager.derived] end
 [DEBUG] 10:59:02.0077 [postpackager.autoload] start
 [ERROR] Cannot read property 'useAutoload' of undefined
C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis\node_modules\fis-command-release\release.js:201
                throw e;
                      ^
TypeError: Cannot read property 'useAutoload' of undefined
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis-postpackager-autoload\index.js:389:62
    at Function._.map (C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis\node_modules\fis-kernel\lib\util.js:130:23)
    at module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis-postpackager-autoload\index.js:388:14)
    at cb (C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis\node_modules\fis-kernel\lib\release.js:115:9)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis\node_modules\fis-kernel\lib\util.js:711:17
    at Array.forEach (native)
    at Function._.pipe (C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis\node_modules\fis-kernel\lib\util.js:698:20)
    at Object.module.exports [as release] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis\node_modules\fis-kernel\lib\release.js:131:14)
    at release (C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis\node_modules\fis-command-release\release.js:171:17)
    at Command.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis\node_modules\fis-command-release\release.js:351:17)

**Comment by hefangshi** [comment]
autoload插件已经发布0.1.1解决这个问题

```
npm i -g fis-postpackager-autoload@0.1.1
```
```

**Comment by yongsudehanzi** [comment]
ok， 敬上深深的谢意
