### ISSUE TITLE
使用http-push部署上传出错

### ISSUE THREAD

**Issue by libofei2004** [fex-team/fis#725]
使用http-push上传的时候有时会出错报如下，并非每次都会，有时会，不知何故？

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1010:19)

**Comment by hefangshi** [comment]
检查后端服务器的情况吧，这里显示的是连接超时。

**Comment by libofei2004** [comment]
ok
