### ISSUE TITLE
fis支不支持nodejs 6.0?

### ISSUE THREAD

**Issue by vinceyi** [fex-team/fis#752]
nodejs升级到6.0  fis挂了

---

$  fis3 -v
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:801:5)
    at Liftoff.buildEnvironment (C:\Users\yi\AppData\Roaming\npm\node_modules\fis3\node_modules\liftoff\index.js:113:52)
    at Liftoff.<anonymous> (C:\Users\yi\AppData\Roaming\npm\node_modules\fis3\node_modules\liftoff\index.js:185:28)
    at Liftoff.<anonymous> (C:\Users\yi\AppData\Roaming\npm\node_modules\fis3\node_modules\liftoff\index.js:153:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3

---

**Comment by liujb** [comment]
我也遇到这个问题了，请问如何解？

**Comment by xiangshouding** [comment]
正在适配

**Comment by hefangshi** [comment]
fis@1.10.0 已经支持了 Node.js 6.x

**Comment by hitao123** [comment]
同遇到这个错误

**Comment by xiangshouding** [comment]
把错误贴出来，如果新升级了 node 请重新装一次 fis

hitao123 <notifications@github.com>于2017年1月13日周五 17:45写道：

**Comment by hitao123** [comment]
![cqazo ye4 epeux t5 khg](https://cloud.githubusercontent.com/assets/16607714/21968332/88ae8e16-dbce-11e6-936c-65bca5d21aba.png)
现在重新安装一遍fis3 ，没问题了，谢谢
![x_3m wwq hx pmv2y d8n](https://cloud.githubusercontent.com/assets/16607714/21968512/5046f6ce-dbd0-11e6-9072-09225c8e141c.png)
