### ISSUE TITLE
Windows 下 Cmder 执行 fis3 报错

### ISSUE THREAD

**Issue by aOrz** [fex-team/fis#776]
C:\Users\Administrator\AppData\Roaming\npm\fis3:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Liftoff.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis3\bin\fis.js:26:11)
    at Liftoff.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis3\node_modules\liftoff\index.js:197:12)
模拟的 linux 环境好像有些问题

**Comment by YuZhaoping** [comment]
我遇到了同样的问题：
U:\node\global\fis3:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Liftoff.<anonymous> (U:\node\global\node_modules\fis3\bin\fis.js:26:11)
我把U:\node\global\（npm全局包安装目录）下的fis3删除，只剩下fis3.cmd后，这个问题不出现了。
