### ISSUE TITLE
请问下，我cnpm安装成功了fis3 但是fis3 命令报错，也添加到了环境变量

### ISSUE THREAD

**Issue by JerryMark1** [fex-team/fis#809]
$ fis3 -v
D:\projects\env\frontent\npm\fis3:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Liftoff.<anonymous> (D:\projects\env\frontent\npm\node_modules\fis3\bin\fis.js:26:11)

**Comment by xiangshouding** [comment]
用 npm 安装啊。
